config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as:'about'
  resources :study_times,only:[:new,:create,:show,:destroy]
  get 'study_time/:id' => 'study_times#daily_show' ,as:'daily_show'
  resources :recommends do
    resource :favorites, only: [:create, :destroy]
    resources :recommend_comments, only: [:create, :destroy]
  end
  resources :users, only:[:show,:edit,:update,:index] do
    member do
      patch 'start'
      patch 'stop'
    end
  end
  resources :posts, except:[:show, :index]do
    resources :posts_comments, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  delete 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す

  get 'follows' => 'follows#index', as:'follows'
  get 'follows/timeline' => 'follows#timeline' ,as:'timeline'

  get 'weekly' => 'rankings#ranking' ,as:'ranking'


  get 'search' => 'recommends#search'
  get 'search/rakuten' => 'recommends#rakuten_search', as:'rakuten_search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recommend
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image
  belongs_to :user

  validates :body, presence: true
end

app/models/recommend.rb
class Recommend < ApplicationRecord
  belongs_to :user
  has_many :recommend_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :outher, presence: true
  validates :publisher, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/recommend_comment.rb
class RecommendComment < ApplicationRecord
  belongs_to :user
  belongs_to :recommend

  validates :recommend_comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "following_id"
  belongs_to :followed, class_name: "User"
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  belongs_to :user

  validates :min, presence: true
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :study_times, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :recommend_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :follower, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy # フォローする際必要な記述
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォローされる際必要な記述？
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている
  has_many :followed_uesr, through: :followed, source: :follower # 自分がフォローされている
  has_many :posts, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true

  def follow(user) # フォローする。other_user = paramsで取得するフォローしたいユーザー
    follower.create(followed_id: user)
  end

  def unfollow(user) # フォローを外す
    target_relationship = follower.find_by(followed_id: user)
    target_relationship.destroy if target_relationship
  end

  def following?(user) # フォローしているかどうかの確認
    following_user.include?(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    user = current_user
    @post.user_id = user.id
    if @post.save
      flash[:notice] = "ひとりごとを言いました"
      redirect_to user_path(user)
    else
      render new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to user_path(user)
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿内容を変更しました。"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to user_path(current_user)
  end

  def index
    @posts = Post.all.page(params[:page]).order(id: "DESC").per(5)
  end

  private

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/controllers/recommends_controller.rb
class RecommendsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @recommend = Recommend.new
  end

  def create
    @recommend = Recommend.new(recommend_params)
    @recommend.user_id = current_user.id
    if @recommend.save
      flash[:notice] = "投稿が完了しました。"
      redirect_to recommend_path(@recommend.id)
    else
      render :new
    end
  end

  def show
    @recommend = Recommend.find(params[:id])
    @recommend_comment = RecommendComment.new
  end

  def index
    @recommends = Recommend.all.page(params[:page]).order(created_at: "DESC").per(10)
  end

  def edit
    @recommend = Recommend.find(params[:id])
    if @recommend.user != current_user
      redirect_to recommends_path
    end
  end

  def update
    @recommend = Recommend.find(params[:id])
    if @recommend.update(recommend_params)
      flash[:notice] = "投稿内容を変更しました。"
      redirect_to recommend_path(@recommend.id)
    else
      render :edit
    end
  end

  def destroy
    @recommend = Recommend.find(params[:id])
    @recommend.delete
    flash[:notice] = "投稿を削除しました。"
    redirect_to recommends_path
  end

  def search
    if params[:keyword].present?
      @recommends = Recommend.where('title LIKE ?', "%#{params[:keyword]}%")
    else
      @recommends = Recommend.none
    end
  end

  def rakuten_search
    if params[:keyword]
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
    end
  end

  private

  def recommend_params
    params.require(:recommend).permit(:title, :outher, :publisher, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @study_times = @user.study_times
    @recommends = @user.recommends.page(params[:page]).reverse_order.per(10)
    @studying_users = User.where(is_active: true).limit(3).order(updated_at: "DESC")
    @posts = @user.posts.page(params[:page]).reverse_order.per(5)
    d = Date.today
    @weekly_times = StudyTime.where("study_date": d.all_week).where("user_id": params[:id]).all.sum(:min) / 60.0
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "編集内容を保存しました。"
      redirect_to user_path
    else
      render :edit
    end
  end

  def start
    @user = current_user
    @user.update(user_params)
  end

  def stop
    @user = current_user
    @user.update(user_params)
  end

  def index # 勉強中ユーザ一覧
    @studying_users = User.where(is_active: true).order(updated_at: "DESC")
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :is_active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/study_times_helper.rb
module StudyTimesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recommends/_favorite.html.erb
<% if recommend.favorited_by?(current_user) %>
    <p>
      <%= link_to recommend_favorites_path(recommend) ,method: :delete ,remote: true do %>
      <i class="fas fa-heart favorite"></i><span class="favorite"><%= recommend.favorites.count %></span>
      <% end %>
    </p>
<% else %>
    <p>
      <%= link_to recommend_favorites_path(recommend), method: :post ,remote: true do %>
      <i class="far fa-heart favorite"></i><%= recommend.favorites.count %>
      <% end %>
    </p>
<% end %>

app/views/recommends/_rakuten_search.html.erb
<p class="pt-3 h4">楽天市場で検索</p>
<div class="pb-3">
  <%= form_tag :rakuten_search, method: :get do  %>
    <%= text_field_tag 'keyword', params[:keyword],placeholder:"タイトル検索" %>
    <%= submit_tag "検索" %>
  <% end %>
</div>

app/views/recommends/_recommend.error.html.erb
  <div class="error">
    <% if @recommend.errors.any? %>
      <%= @recommend.errors.count %>件のエラーが発生しました
      <% @recommend.errors.full_messages.each do |message| %>
      <div>
        <%= message %>
      </div>
      <% end %>
    <% end %>
  </div>

app/views/recommends/edit.html.erb
<%= render partial: 'recommends/recommend.error' %>

<table class="edit-recommend">
  <%= form_with model:@recommend, local:true do |f| %>
    <tr>
      <th>タイトル<td><%= f.text_field :title %></td></th>
    </tr>
    <tr>
      <th>著者<td><%= f.text_field :outher %></td></th>
    </tr>
    <tr>
      <th>出版社<td><%= f.text_field :publisher %></td></th>
    </tr>
    <tr>
      <th>コメント<td><%= f.text_area :body %></td></th>
    </tr>
    <tr>
      <th><td><%= f.submit "編集内容を登録する",class:"btn btn-success post-btn" %></td></th>
    </tr>
    <% end %>
</table>

app/views/recommends/index.html.erb
<div class="container">
    <h1 class="text-center">おすすめ書籍一覧</h1>

    <div class="text-center p-5">
        <%= link_to "書籍新規登録" ,new_recommend_path ,class:"btn btn-success" %>
    </div>
    <div class="search-form inline-block">
        <p>おすすめ書籍内から検索</p>
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, value: @keyword ,placeholder:"タイトル検索" %>
            <%= f.submit "検索" %>
          <% end %>
    </div>

    <div class="search-form inline-block">
        <p>楽天市場で検索</p>
        <%= form_tag :rakuten_search, method: :get do  %>
          <%= text_field_tag 'keyword', params[:keyword],placeholder:"タイトル検索" %>
          <%= submit_tag "検索" %>
        <% end %>
    </div>

    <table border="1" style="border-collapse: collapse", class="recommend-table">
        <tr>
            <th class="items recommend-title">タイトル</th>
            <th class="items recommend-outher">著者</th>
            <th class="items recommend-publisher">出版社</th>
            <th class="items recommend-comment">コメント</th>
            <th class="items recommend-user">投稿者</th>
            <th class="items recommend-favorite"></th>
        </tr>
        <% @recommends.each do |recommend| %>
        <tr>
            <td>
                <%= link_to recommend.title,recommend_path(recommend.id), class:"no-underline" %>
            </td>
            <td>
                <%= recommend.outher %>
            </td>
            <td>
                <%= recommend.publisher %>
            </td>
            <td>
                <%= recommend.body %>
            </td>
            <td>
                <%= recommend.user.name %>
            </td>
            <td>
                <i class="fas fa-heart favorite"></i><span class="favorite"><%= recommend.favorites.count %>
            </td>
        </tr>
        <% end %>
        <%= paginate @recommends %>
    </table>
</div>

app/views/recommends/new.html.erb
<%= render partial: 'recommends/recommend.error' %>

<div class="text-center">
  <%= form_with model:@recommend, local:true do |f| %>
    <p>
      <%= f.text_field :title, placeholder:"タイトル" %>
    </p>
    <p>
      <%= f.text_field :outher, placeholder:"著者" %>
    </p>
    <p>
      <%= f.text_field :publisher, placeholder:"出版社" %>
    </p>
    <div>
        <%= f.text_area :body, placeholder:"コメント",class:"text-area" %>
    </div>
    <%= f.submit"登録する", class:"btn btn-success post-btn" %>
  <% end %>
</div>

app/views/recommends/rakuten_search.html.erb
<div class="container">
  <%= render partial: 'recommends/rakuten_search' %>
  <table>
    <thead>
      <tr>
        <th>商品名</th>
        <th>価格</th>
      </tr>
    </thead>
    <tbody>
      <% if @items.present? %>
        <% @items.first(10).each do |item| %>
          <tr>
            <td><%= link_to item.name, "#{item.url}" %></td>
            <td align="right"><%= number_with_delimiter(item.price) %>円</td>
          </tr>
          <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recommends/search.html.erb
<div class="container">
    <h1>検索結果</h1>
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword ,placeholder:"タイトル検索"%>
      <%= f.submit "検索" %>
    <% end %>

    <table>
        <tr>
            <th>タイトル</th>
            <th>著者</th>
            <th>出版社</th>
            <th>コメント</th>
            <th>投稿者</th>
            <th></th>
        </tr>
        <% @recommends.each do |recommend| %>
        <tr>
            <td>
                <%= link_to recommend.title,recommend_path(recommend.id), class:"no-underline" %>
            </td>
            <td>
                <%= recommend.outher %>
            </td>
            <td>
                <%= recommend.publisher %>
            </td>
            <td>
                <%= recommend.body %>
            </td>
            <td>
                <%= recommend.user.name %>
            </td>
            <td>
                <i class="fas fa-heart favorite"></i><span class="favorite"><%= recommend.favorites.count %>
            </td>

        </tr>
        <% end %>
    </table>
</div>

app/views/recommends/show.html.erb
<div class="container">

  <div class="card card-recommend">
    <div class="card-content">
      <h1 class="card-title">『<%= @recommend.title %>』</h1>
      <h6 class="recommend-info">
        出版社　<%= @recommend.publisher %></br>
        著者　<%= @recommend.outher %>
      </h6>
      <div>投稿者 :
        <%= link_to user_path(@recommend.user.id), class:"no-underline" ,method: :get do %>
          <%= attachment_image_tag @recommend.user, :profile_image, fallback:"no_image.jpg",class:"mt-3 rounded-circle border user-image" %>
          <%= @recommend.user.name %>
        <% end %>
        <%= @recommend.updated_at.strftime("%Y/%m/%e %H:%M") %>
      </div>
      <div>投稿者コメント：
        <%= @recommend.body %>
      </div>
      <div id="favorites_buttons_<%= @recommend.id %>">
     <%= render partial: 'recommends/favorite', locals: { recommend: @recommend } %>
  </div>
    </div>
    <% if @recommend.user == current_user %>
      <%= link_to edit_recommend_path(@recommend.id), class:"no-underline" do %>
        編集<i class="fas fa-edit"></i>
      <% end %>
      <%= link_to recommend_path(@recommend.id), class:"no-underline", method: :delete,"data-confirm"=>"削除しますか？" do %>
        削除<i class="fas fa-trash-alt"></i>
      <% end %>
    <% end %>
  </div>

  <%= render partial: 'recommends/rakuten_search' %>

  <div class="error">
    <% if @recommend_comment.errors.any? %>
      <%= @recommend_comment.errors.count %>件のエラーが発生しました
      <% @recommend_comment.errors.full_messages.each do |message| %>
      <div>
        <%= message %>
      </div>
      <% end %>
    <% end %>
  </div>

  <%= form_with(model:[@recommend, @recommend_comment], method: :post,local: true) do |f| %>
    <p class="pt-3">
      <%= f.text_field :recommend_comment,placeholder:"コメントを入力" %>
      <%= f.submit"コメントする" %>
    </p>
  <% end %>

    <p>コメント件数：<%= @recommend.recommend_comments.count %></p>

    <table>
      <% @recommend.recommend_comments.each do |recommend_comment| %>
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td>
          <%= link_to user_path(recommend_comment.user.id), class:"no-underline", method: :get do %>
          <%= attachment_image_tag recommend_comment.user, :profile_image, fallback:"no_image.jpg",class:"mt-3 rounded-circle border user-image" %>
          <%= recommend_comment.user.name %>
          <% end %>
        </td>
        <td>
          <%= recommend_comment.recommend_comment %>
        </td>
        <td>
          <%= recommend_comment.updated_at.strftime("%Y/%m/%e %H:%M") %>
        </td>
        <td>
          <% if recommend_comment.user == current_user %>
            <%= link_to "#{@recommend.id}/recommend_comments/#{recommend_comment.id}", class:"no-underline", method: :delete,"data-confirm"=>"コメントを削除しますか？" do %>
              削除<i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>

</div>