config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as:'about'
  resources :study_times,only:[:new,:create,:show,:destroy]
  get 'study_time/:id' => 'study_times#daily_show' ,as:'daily_show'
  resources :recommends do
    resource :favorites, only: [:create, :destroy]
    resources :recommend_comments, only: [:create, :destroy]
  end
  resources :users, only:[:show,:edit,:update,:index] do
    member do
      patch 'start'
      patch 'stop'
    end
  end
  resources :posts, except:[:show, :index]do
    resources :posts_comments, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  delete 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す

  get 'follows' => 'follows#index', as:'follows'
  get 'follows/timeline' => 'follows#timeline' ,as:'timeline'

  get 'weekly' => 'rankings#ranking' ,as:'ranking'


  get 'search' => 'recommends#search'
  get 'search/rakuten' => 'recommends#rakuten_search', as:'rakuten_search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recommend
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image
  belongs_to :user

  validates :body, presence: true
end

app/models/recommend.rb
class Recommend < ApplicationRecord
  belongs_to :user
  has_many :recommend_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :outher, presence: true
  validates :publisher, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/recommend_comment.rb
class RecommendComment < ApplicationRecord
  belongs_to :user
  belongs_to :recommend

  validates :recommend_comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "following_id"
  belongs_to :followed, class_name: "User"
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  belongs_to :user

  validates :min, presence: true
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :study_times, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :recommend_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :follower, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy # フォローする際必要な記述
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォローされる際必要な記述？
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている
  has_many :followed_uesr, through: :followed, source: :follower # 自分がフォローされている
  has_many :posts, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true

  def follow(user) # フォローする。other_user = paramsで取得するフォローしたいユーザー
    follower.create(followed_id: user)
  end

  def unfollow(user) # フォローを外す
    target_relationship = follower.find_by(followed_id: user)
    target_relationship.destroy if target_relationship
  end

  def following?(user) # フォローしているかどうかの確認
    following_user.include?(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    user = current_user
    @post.user_id = user.id
    if @post.save
      flash[:notice] = "ひとりごとを言いました"
      redirect_to user_path(user)
    else
      render new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to user_path(user)
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿内容を変更しました。"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to user_path(current_user)
  end

  def index
    @posts = Post.all.page(params[:page]).order(id: "DESC").per(5)
  end

  private

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/controllers/study_times_controller.rb
class StudyTimesController < ApplicationController
  def new
    @study_time = StudyTime.new
  end

  def create
    @study_time = StudyTime.new
    @study_time.user_id = current_user.id
    @study_time.study_date = Date.today
    @study_time.comment = params[:study_time][:comment]
    hour = params[:study_time][:hour].to_i * 60
    min = params[:study_time][:min]
    @study_time.min = hour.to_i + min.to_i
    if @study_time.save
      redirect_to study_time_path(current_user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @all_study_times = @user.study_times
    @daily_times = StudyTime.where(user_id: @user.id).group("study_date").order("study_date DESC").all.sum(:min)
  end

  def daily_show
    @date = params[:id].to_s
    @daily_study_details = StudyTime.where(user_id: current_user.id, study_date: @date)
  end

  def destroy
    @study_time = StudyTime.find(params[:id])
    @study_time.destroy
    redirect_to daily_show_path(@study_time.study_date)
  end

  private

  def study_time_params
    params.require(:study_time).permit(:year, :date, :hour, :min, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @study_times = @user.study_times
    @recommends = @user.recommends.page(params[:page]).reverse_order.per(10)
    @studying_users = User.where(is_active: true).limit(3).order(updated_at: "DESC")
    @posts = @user.posts.page(params[:page]).reverse_order.per(5)
    d = Date.today
    @weekly_times = StudyTime.where("study_date": d.all_week).where("user_id": params[:id]).all.sum(:min) / 60.0
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "編集内容を保存しました。"
      redirect_to user_path
    else
      render :edit
    end
  end

  def start
    @user = current_user
    @user.update(user_params)
  end

  def stop
    @user = current_user
    @user.update(user_params)
  end

  def index # 勉強中ユーザ一覧
    @studying_users = User.where(is_active: true).order(updated_at: "DESC")
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :is_active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/study_times_helper.rb
module StudyTimesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/study_times/daily_show.html.erb
<div class="container">
  <div class="text-center">
    <%= @date %>の勉強内容詳細
  </div>
  <table class="times-table">
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @daily_study_details.each do |daily_study_detail| %>
    <tr class="border-bottom">
      <td>
         <%= daily_study_detail.comment %>
      </td>
      <td class="p-4">
        <%= (daily_study_detail.min/60.0).floor(2) %>時間
      </td>
      <td>
        <% if daily_study_detail.user == current_user %>
          <%= link_to study_time_path(daily_study_detail.id), class:"no-underline", method: :delete do %>
          <i class="fas fa-trash-alt"></i>削除
          <% end %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/study_times/index.html.erb
<h1>勉強時間一覧画面</h1>
<h2>今日は<%= @total_time %>時間勉強しました</h2>
<h2>今週は時間勉強しました</h2>
<% @study_times.each do |studey_time| %>
<%= studey_time.year %>年
<%= studey_time.month %>月
<%= studey_time.date %>日
<%= studey_time.hour %>時間
<%= studey_time.min %>分
<div>コメント
    <%= studey_time.comment %>
</div>
<div>
    <%= link_to "編集する",edit_study_time_path(studey_time.id) %>
</div>

<% end %>

app/views/study_times/new.html.erb
  <div class="error">
    <% if @study_time.errors.any? %>
      <%= @study_time.errors.count %>件のエラーが発生しました
      <% @study_time.errors.full_messages.each do |message| %>
      <div>
        <%= message %>
      </div>
      <% end %>
    <% end %>
  </div>

  <div class="study-time">
    <%= form_with model:@study_time, local:true do |f| %>
      <div class="text-left">
        <%= f.text_field :hour, class:"input-studytime", placeholder:"半角入力" %>時間
      </div>
      <div class="text-left">
        <%= f.text_field :min, class:"input-studytime", placeholder:"半角入力" %>分
      </div>
      <div  class="text-left">
        <%= f.text_field :comment,placeholder:"勉強内容" %>
      </div>
      <div class="text-center">
        <%= f.submit"登録する",class:"btn btn-success post-btn"  %>
      </div>
    <% end %>
  </div>

app/views/study_times/show.html.erb
<div class="container">
  <h1><%= @user.name %>の勉強時間一覧</h1>

  <% @daily_times.each do |date , min| %>
    <% if @user == current_user %>
      <p class="border-bottom">
        <%= date %>
        <%= link_to (min/60.0).floor(1),daily_show_path(date) %>時間
      </p>
    <% else %>
      <p class="border-bottom">
        <%= date %>
        <%= (min/60.0).floor(1) %>時間
      </p>
    <% end %>
  <% end %>
</div>