config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as:'about'
  resources :study_times,only:[:new,:create,:show,:destroy]
  get 'study_time/:id' => 'study_times#daily_show' ,as:'daily_show'
  resources :recommends do
    resource :favorites, only: [:create, :destroy]
    resources :recommend_comments, only: [:create, :destroy]
  end
  resources :users, only:[:show,:edit,:update,:index] do
    member do
      patch 'start'
      patch 'stop'
    end
  end
  resources :posts, except:[:show, :index]do
    resources :posts_comments, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  delete 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す

  get 'follows' => 'follows#index', as:'follows'
  get 'follows/timeline' => 'follows#timeline' ,as:'timeline'

  get 'weekly' => 'rankings#ranking' ,as:'ranking'


  get 'search' => 'recommends#search'
  get 'search/rakuten' => 'recommends#rakuten_search', as:'rakuten_search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recommend
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image
  belongs_to :user

  validates :body, presence: true
end

app/models/recommend.rb
class Recommend < ApplicationRecord
  belongs_to :user
  has_many :recommend_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :outher, presence: true
  validates :publisher, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/recommend_comment.rb
class RecommendComment < ApplicationRecord
  belongs_to :user
  belongs_to :recommend

  validates :recommend_comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "following_id"
  belongs_to :followed, class_name: "User"
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  belongs_to :user

  validates :min, presence: true
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :study_times, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :recommend_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :follower, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy # フォローする際必要な記述
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォローされる際必要な記述？
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている
  has_many :followed_uesr, through: :followed, source: :follower # 自分がフォローされている
  has_many :posts, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true

  def follow(user) # フォローする。other_user = paramsで取得するフォローしたいユーザー
    follower.create(followed_id: user)
  end

  def unfollow(user) # フォローを外す
    target_relationship = follower.find_by(followed_id: user)
    target_relationship.destroy if target_relationship
  end

  def following?(user) # フォローしているかどうかの確認
    following_user.include?(user)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def index
    @follow_users = current_user.following_user
  end

  def timeline
    @follow_users = current_user.following_user
    @posts = Post.where(user_id: @follow_users).page(params[:page]).order(created_at: "DESC").per(20)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    user = current_user
    @post.user_id = user.id
    if @post.save
      flash[:notice] = "ひとりごとを言いました"
      redirect_to user_path(user)
    else
      render new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to user_path(user)
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿内容を変更しました。"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to user_path(current_user)
  end

  def index
    @posts = Post.all.page(params[:page]).order(id: "DESC").per(5)
  end

  private

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @study_times = @user.study_times
    @recommends = @user.recommends.page(params[:page]).reverse_order.per(10)
    @studying_users = User.where(is_active: true).limit(3).order(updated_at: "DESC")
    @posts = @user.posts.page(params[:page]).reverse_order.per(5)
    d = Date.today
    @weekly_times = StudyTime.where("study_date": d.all_week).where("user_id": params[:id]).all.sum(:min) / 60.0
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "編集内容を保存しました。"
      redirect_to user_path
    else
      render :edit
    end
  end

  def start
    @user = current_user
    @user.update(user_params)
  end

  def stop
    @user = current_user
    @user.update(user_params)
  end

  def index # 勉強中ユーザ一覧
    @studying_users = User.where(is_active: true).order(updated_at: "DESC")
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :is_active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/study_times_helper.rb
module StudyTimesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_post.error.html.erb
<div class="error">
  <% if @post.errors.any? %>
    <%= @post.errors.count %>件のエラーが発生しました
    <% @post.errors.full_messages.each do |message| %>
    <div>
      <%= message %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/posts/_post_index.html.erb
<% @posts.each do | post | %>
    <section class="card">
      <div class="card-content">
        <h1 class="card-title">
            <%= attachment_image_tag post.user, :profile_image, :fill, 70, 70, fallback:"no_image.jpg",class:"mt-3 rounded-circle border user-image" %>
            <%= link_to post.user.name,user_path(post.user.id), class:"no-underline" %>
        </h1>
        <p class="card-text"><%= post.body %></p>
      </div>
      <%= attachment_image_tag post, :image, class:"card-img" %>
      <% if post.user == current_user %>
          <div class="card-link">
              <%= link_to edit_post_path(post.id), class:"no-underline" do %>
                編集<i class="fas fa-edit"></i>
              <% end %>
              <%= link_to post_path(post.id),method: :delete,"data-confirm"=>"削除しますか？" , class:"no-underline" do %>
                削除<i class="fas fa-trash-alt"></i>
              <% end %>
          </div>
      <% end %>
      <h7><%= post.updated_at.strftime("%Y/%m/%e %H:%M") %></h7>
    </section>
<% end %>
<%= paginate @posts %>

app/views/posts/edit.html.erb
<%= render partial: 'posts/post.error' %>

<div class="text-center">
  <%= form_with model:@post, local:true do |f| %>
    <div>
       <%= f.text_area :body, class:"text-area" %>
    </div>
    <div>
       <%= f.attachment_field :image %>
    </div>
    <div>
      <%= f.submit "更新", class:"btn btn-success post-btn" %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render partial: 'posts/post.error' %>

<div class="text-center">
  <h3>ひとりごとを言う</h3>
  <%= form_with model:@post, local:true do |f| %>
  <div>
    <%= f.text_area :body , placeholder:"ひとりごと", class:"text-area" %>
  </div>
  <div>
    <%= f.attachment_field :image, placeholder: "プロフィール画像" %>
  </div>
  <div>
    <%= f.submit"つぶやく",class:"btn btn-success post-btn" %>
  </div>
  <% end %>
</div>

app/views/users/_is_active.html.erb
<% if @user.is_active == true %>
        <%= form_with model: @user, url:stop_user_path,remote:true do |f| %>
        <%= f.hidden_field :is_active, value: false %>
        <%= f.submit" 勉強終了 ",class:"btn btn-danger" %>
        <% end %>
    <% else %>
        <%= form_with model: @user, url:start_user_path,remote:true do |f| %>
        <%= f.hidden_field :is_active, value: true %>
        <%= f.submit" 勉強開始 ",class:"btn btn-success" %>
        <% end %>
<% end %>

app/views/users/_relationship.html.erb
   <% if current_user.following?(user) %>
       <p>
         <%= link_to unfollow_path(user) ,method: :delete ,remote: true do %>
         <span class="btn btn-primary">フォローを外す</span>
         <% end %>
       </p>
    <% else %>
       <p>
         <%= link_to follow_path(user) ,method: :post ,remote: true do %>
        <span class="btn btn-success">フォローする</span>
         <% end %>
       </p>
    <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <h1>プロフィールを編集</h1>
    </div>
  </div>

  <div class="error">
    <% if @user.errors.any? %>
      <%= @user.errors.count %>件のエラーが発生しました
      <% @user.errors.full_messages.each do |message| %>
      <div>
        <%= message %>
      </div>
      <% end %>
    <% end %>
  </div>

  <%= form_with model:@user, local:true do |f| %>
  <div class="row sign-field">
    <div class="col text-center">
      <div>
        <label for="inputName">名前</label>
      </div>
      <div>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      </div>
    </div>
  </div>
  <div class="row sign-field">
    <div class="col text-center">
      <div>
        <label for="introduction">自己紹介</label>
      </div>
      <div>
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介", size:"300px"%>
      </div>
    </div>
  </div>
  <div class="row sign-field">
    <div class="col text-center">
      <div>
        <label for="inputImage">アイコン画像</label>
      </div>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback:"no_image.jpg" %>
      <div>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit "変更を保存",class:"btn btn-success post-btn" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="text-center">
  <h1>勉強中ユーザ一覧</h1>
  </div>
      <% @studying_users.each do |user| %>
      <div class="studying-users">
        <div class="row w-70 border-bottom">
          <div class="col-3">
            <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback:"no_image.jpg", class:"mt-3 rounded-circle border" %>
            <%= link_to user.name,user_path(user.id) %>
            <% if user != current_user %>
              <div id="follow_buttons_<%= user.id %>" >
                <%= render partial: 'users/relationship', locals: { user: user } %>
              </div>
            <% end %>
          </div>
          <div class="col-7 introduction">
            <%= user.introduction %>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col profile">
            <div>
                <div class="profile-image">
                    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg", class:"mt-3 rounded-circle border" %>
                </div>
                <h3 class="profile-name">
                    <%= @user.name %>
                </h3>
                <div class="introduction">
                     <%= @user.introduction %>
                </div>
                <div>
                     <% if @user == current_user %>
                        <%= link_to edit_user_path(@user.id), class:"no-underline" do %>
                          プロフィールを編集<i class="fas fa-edit"></i>
                        <% end %>
                     <% end %>
                 </div>
                 <% if @user == current_user %>
                    <div id="is_active_buttons_<%= @user.id %>" class="btn">
                        <%= render partial: 'users/is_active', locals: { user: @user } %>
                    </div>
                    <div class="btn">
                        <%= link_to "勉強時間をみる" ,study_time_path(@user.id), class:"btn btn-secondary" %>
                    </div>
                    <div class="btn">
                        <%= link_to "ひとりごとをいう" , new_post_path, class:"btn btn-secondary" %>
                    </div>
                <% else %>
                    <div class="btn">
                        <%= link_to "勉強時間をみる" ,study_time_path(@user.id), class:"btn btn-secondary" %>
                    </div>
                    <div id="follow_buttons_<%= @user.id %>">
                       <%= render partial: 'users/relationship', locals: { user: @user } %>
                    </div>
                    <% if @user.is_active == true %>
                        <p><%= @user.name %>さんは勉強中です</p>
                    <% else %>
                        <p><%= @user.name%>さんは休憩中です</p>
                    <% end %>
                <% end%>
            </div>
        </div>
    </div>

    <div class="card mt-3 mb-3 user-syudy-time">
        <div class="card-body m-3">
            <p>今週は<%= @weekly_times.floor(2) %>時間勉強しました!</p>
               <% if @user == current_user %>
                   <%= link_to "勉強時間を登録する" ,new_study_time_path, class:"btn btn-secondary" %>
               <% end %>
        </div>
    </div>

    <div class="row">
        <div class="col text-center">
            <% if @user == current_user %>
                <% @studying_users.each do |user| %>
                    <%= link_to user.name,user_path(user.id), class:"no-underline" %>
                <% end %>
                さんたちをはじめ、<%= @studying_users.count %>人が勉強中です！
                <%= link_to "勉強中ユーザをもっと見る",users_path, class:"no-underline" %>
            <% end %>
        </div>
    </div>

    <div class="row pt-5">
        <div class="col-lg-6">
            <div>投稿書籍一覧
                <table>
                    <tr>
                        <th></th>
                        <th></th>
                    </tr>
                    <% @recommends.each do |recommend| %>
                    <tr>
                        <td>
                            <%= link_to recommend.title,recommend_path(recommend.id), class:"no-underline" %>
                        </td>
                        <td>
                            <i class="fas fa-heart favorite"></i><%= recommend.favorites.count %>
                        </td>
                    </tr>
                    <% end %>
                    <%= paginate @recommends %>
                </table>
            </div>
        </div>
        <div class="col-lg-6">
            <div>ひとりごと一覧
            <%= render partial: 'posts/post_index' %>
            </div>
        </div>
    </div>
</div>

app/views/users/start.js.erb
$('#is_active_buttons_<%= @user.id %>').html("<%= escape_javascript(render partial: 'users/is_active', locals: {user: @user}) %>");

app/views/users/stop.js.erb
$('#is_active_buttons_<%= @user.id %>').html("<%= escape_javascript(render partial: 'users/is_active', locals: {user: @user}) %>");