config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as:'about'
  resources :study_times,only:[:new,:create,:show,:destroy]
  get 'study_time/:id' => 'study_times#daily_show' ,as:'daily_show'
  resources :recommends do
    resource :favorites, only: [:create, :destroy]
    resources :recommend_comments, only: [:create, :destroy]
  end
  resources :users, only:[:show,:edit,:update,:index] do
    member do
      patch 'start'
      patch 'stop'
    end
  end
  resources :posts, except:[:show, :index]do
    resources :posts_comments, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  delete 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す

  get 'follows' => 'follows#index', as:'follows'
  get 'follows/timeline' => 'follows#timeline' ,as:'timeline'

  get 'weekly' => 'rankings#ranking' ,as:'ranking'


  get 'search' => 'recommends#search'
  get 'search/rakuten' => 'recommends#rakuten_search', as:'rakuten_search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recommend
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image
  belongs_to :user

  validates :body, presence: true
end

app/models/recommend.rb
class Recommend < ApplicationRecord
  belongs_to :user
  has_many :recommend_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :outher, presence: true
  validates :publisher, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/recommend_comment.rb
class RecommendComment < ApplicationRecord
  belongs_to :user
  belongs_to :recommend

  validates :recommend_comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "following_id"
  belongs_to :followed, class_name: "User"
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  belongs_to :user

  validates :min, presence: true
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :study_times, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :recommend_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :follower, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy # フォローする際必要な記述
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォローされる際必要な記述？
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている
  has_many :followed_uesr, through: :followed, source: :follower # 自分がフォローされている
  has_many :posts, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true

  def follow(user) # フォローする。other_user = paramsで取得するフォローしたいユーザー
    follower.create(followed_id: user)
  end

  def unfollow(user) # フォローを外す
    target_relationship = follower.find_by(followed_id: user)
    target_relationship.destroy if target_relationship
  end

  def following?(user) # フォローしているかどうかの確認
    following_user.include?(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    user = current_user
    @post.user_id = user.id
    if @post.save
      flash[:notice] = "ひとりごとを言いました"
      redirect_to user_path(user)
    else
      render new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to user_path(user)
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿内容を変更しました。"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to user_path(current_user)
  end

  def index
    @posts = Post.all.page(params[:page]).order(id: "DESC").per(5)
  end

  private

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @study_times = @user.study_times
    @recommends = @user.recommends.page(params[:page]).reverse_order.per(10)
    @studying_users = User.where(is_active: true).limit(3).order(updated_at: "DESC")
    @posts = @user.posts.page(params[:page]).reverse_order.per(5)
    d = Date.today
    @weekly_times = StudyTime.where("study_date": d.all_week).where("user_id": params[:id]).all.sum(:min) / 60.0
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "編集内容を保存しました。"
      redirect_to user_path
    else
      render :edit
    end
  end

  def start
    @user = current_user
    @user.update(user_params)
  end

  def stop
    @user = current_user
    @user.update(user_params)
  end

  def index # 勉強中ユーザ一覧
    @studying_users = User.where(is_active: true).order(updated_at: "DESC")
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :is_active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/helpers/study_times_helper.rb
module StudyTimesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TogetherStudy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
         <nav  class="navbar navbar-expand-lg navbar-light">
           <div class="container">
             <%= link_to root_path , method: :get do %>
              <%= image_tag('logo.jpg') %>
             <% end %>
             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
               <div class="hamburger-icon"></div>
             </button>
             <div class="collapse navbar-collapse" id="navbarNavDropdown">
               <ul class="navbar-nav ml-auto">
                 <% if user_signed_in? %>
                 <li class="header-list">
                   <%= link_to user_path(current_user.id), method: :get do%>
                     <i class="far fa-user-circle"></i>マイページ
                   <% end %>
                 </li>
                 <li class="header-list">
                    <%= link_to recommends_path, method: :get do %>
                      <i class="fas fa-book-open"></i>書籍一覧
                    <% end %>
                  </li>
                  <li class="header-list">
                    <%= link_to follows_path, method: :get do %>
                      <i class="fas fa-users"></i>フォローユーザ
                    <% end %>
                  </li>
                  <li class="header-list">
                    <%= link_to users_path, method: :get do %>
                      <i class="fas fa-pencil-alt"></i>勉強中
                    <% end %>
                  </li>
                  <li class="header-list">
                    <%= link_to ranking_path, method: :get do %>
                      <i class="fas fa-crown"></i>ランキング
                    <% end %>
                  </li>
                  <li class="header-list">
                    <%= link_to timeline_path, method: :get do %>
                      <i class="far fa-comment-dots"></i>タイムライン
                    <% end %>
                  </li>
                  <li class="header-list">
                   <%= link_to destroy_user_session_path, method: :delete do %>
                   <i class="fas fa-sign-out-alt"></i>ログアウト
                   <% end %>
                 </li>
                  <% end %>
               </ul>
             </div>
           </div>
         </nav>
      </header>

      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <%= yield %>
      
      <footer></footer>

  </body>
</html>